Add service which work with Firebase. Create page for own Note. Change display list of Notes to Tui Table.
kamenko-gena/fintech2024-notes-list pull request #3
Opened 2024-11-10 21:13 UTC by kamenko-gena

- Создал сервис `firebase-storage-service` для добавления заметки в Firebase - ` addNoteToStorage()`; получения всех заметок из Firebase - `getNotes()`; получения заметки по ID (для динамического роута) - `getNoteById()`; удаления заметки `removeNote()`; обновления заметки после редактирования - `updateNote()`.

- Создал `my-note-page-component` для отдельной страницы под конкретную заметку с динамическим роутом `my-notes/{note.id}` (создал резолвер для этого). В компоненте выводятся данные по заметке, также добавлена возможность удаления заметки и редактирования (через форму создания `create-form-component`).

- Дополнил `create-form-component`: добавил метод отправки формы (обновления) после редактирования `updateForm()`; подстановку исходных значений выполнил через patchValue() полученных через @Input.

- Переделал отображение списка заметок в `notes-list-component` с "Аккардиона" на таблицу Tui Table.

- Изменил название формконтрола в котором чекбокс (неисправность устранена или нет) на более понятное: `solutionChekedControl` изменил на `isCompleted`.

- В сервисе `auth.service` немного доработал `login()`: применил `catchError` (чтобы не падали ошибки в консоль).

- Для `login-form.component` и `registr-form.component` исправил ошибку отображения Tui Alert.

2024-11-11 08:48 UTC, mkozakevich requested changes

2024-11-11 08:48 UTC, mkozakevich commented on src/app/components/create-note-form/create-note-form.component.ts
> +        if (this.note && this.noteFormGroup.valid) {
чтобы код был более читаемым, можно не вкладывать код в блок с условием, а сначала чекнуть условие и вызвать return, если оно не соблюдается

для данного случая это будет выглядеть так:

```
if (!this.note || this.noteFormGroup.invalid) {
    return;
}

// тут остальной код, который сейчас вложен в условие
```

если так делать, то избавишься от одного уровня вложенности и код будет намного более читаемым

2024-11-11 08:48 UTC, mkozakevich commented on src/app/components/notes-list/notes-list.component.html
> +                        <ng-container>
зачем тут контейнер? он же ничего не делает

2024-11-11 08:48 UTC, mkozakevich commented on src/app/components/notes-list/notes-list.component.html
> +    <table tuiTableFilters tuiTable [style.width.rem]="58">
стили так писать не надо) есть же файл со стилями у каждого компонента. Создай класс и напиши туда стили

2024-11-11 08:48 UTC, mkozakevich commented on src/app/components/notes-list/notes-list.component.ts
> +    readonly tableColName = TABLE_COL_NAME_DATA;
да можно сразу в компонент положить, если в шаблоне юзается) смысл создавать переменную вне класса, а потом объявлять пропертю в классе, чтобы просто переложить в нее значение

в константы есть смысл выносить то, что не юзается в шаблоне, поскольку класс и так имеет доступ к ним без объявления проперти внутри него

2024-11-11 08:48 UTC, mkozakevich commented on src/app/components/notes-list/notes-list.component.ts
> +        this.firebaseStorageService.getNotes().subscribe((notes) => {
отписку забыл

2024-11-11 08:48 UTC, mkozakevich commented on src/app/components/pages/my-notes-page/my-note-page/my-note-page.component.html
> +<tui-root>
в tui-root лучше завернуть все приложение сразу в app.component

2024-11-11 08:48 UTC, mkozakevich commented on src/app/components/pages/my-notes-page/my-note-page/my-note-page.component.less
> +.link-block {
можно просто один класс написать, что-то вроде `flex-container`. Какой смысл плодить разные классы, которые одно и то же делают)

2024-11-11 08:48 UTC, mkozakevich commented on src/app/components/pages/my-notes-page/my-note-page/my-note-page.component.ts
> +        this.route.data.subscribe((data) => {
отписку надо

2024-11-11 08:48 UTC, mkozakevich commented on src/app/directives/solution-descript-validator/solution-descript-validator.directive.ts
> +        this.isCompletedControl.valueChanges.subscribe((isChecked: boolean) => {
тож отписки нет

2024-11-11 08:48 UTC, mkozakevich commented on src/app/resolvers/note-id.resolver.ts
> +    state: RouterStateSnapshot,
state можно не объявлять, если не юзается

2024-11-11 19:20 UTC, kamenko-gena commented on src/app/components/create-note-form/create-note-form.component.ts
> +        if (this.note && this.noteFormGroup.valid) {
исправил
также поправил и в аналогичных местах.

2024-11-11 19:20 UTC, kamenko-gena commented on src/app/components/notes-list/notes-list.component.html
> +                        <ng-container>
убрал

2024-11-11 19:20 UTC, kamenko-gena commented on src/app/components/notes-list/notes-list.component.html
> +    <table tuiTableFilters tuiTable [style.width.rem]="58">
поправил

2024-11-11 19:20 UTC, kamenko-gena commented on src/app/components/notes-list/notes-list.component.ts
> +    readonly tableColName = TABLE_COL_NAME_DATA;
исправил

2024-11-11 19:20 UTC, kamenko-gena commented on src/app/components/notes-list/notes-list.component.ts
> +        this.firebaseStorageService.getNotes().subscribe((notes) => {
исправил

2024-11-11 19:21 UTC, kamenko-gena commented on src/app/components/pages/my-notes-page/my-note-page/my-note-page.component.html
> +<tui-root>
завернул
остальные tui-root убрал

2024-11-11 19:21 UTC, kamenko-gena commented on src/app/components/pages/my-notes-page/my-note-page/my-note-page.component.less
> +.link-block {
переделал на flex-container

2024-11-11 19:21 UTC, kamenko-gena commented on src/app/components/pages/my-notes-page/my-note-page/my-note-page.component.ts
> +        this.route.data.subscribe((data) => {
исправил

2024-11-11 19:21 UTC, kamenko-gena commented on src/app/directives/solution-descript-validator/solution-descript-validator.directive.ts
> +        this.isCompletedControl.valueChanges.subscribe((isChecked: boolean) => {
исправил, отписался в дестрое

2024-11-11 19:21 UTC, kamenko-gena commented on src/app/resolvers/note-id.resolver.ts
> +    state: RouterStateSnapshot,
убрал

2024-11-12 07:36 UTC, mkozakevich approved these changes

2024-11-12 08:00 UTC, merged